name: Docker Dev

# Run workflow on commits to the `master` branch
on:
  push:
    branches:
      - dev

jobs:
  docker:
    runs-on: ubuntu-18.04
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Java and Maven
        uses: actions/setup-java@v3.3.0
        with:
          distribution: 'zulu'
          java-version: '11'

      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots package

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_KEY }}

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v5.2

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./digiwf-okewo-integration-service
          push: true
          tags: itatm/digiwf-address-service-integration-service:${{ steps.branch-name.outputs.current_branch }}